export * as Home from './home.webp';
export * as Chat from './chat.webp';
export * as Cv from './cv.webp'
export * as Ads from './ads.webp'
export * as BriefCase from './briefcase.webp'
export * as Notification from './notification.webp'
export * as Payment from './payment.svg'
export * as Save from './save.webp'
export * as Search from './search.png'
export * as Supplier from './supplier.webp'
export * as Vc from './vc.webp'
export * as Wallet from './wallet.png'
export * as Back from './back.svg'
export * as Gst from './gst-icon.svg'
export * as TimeIcon from './time-icon.svg'
export * as EyeIcon from './eye-icon.svg'
export * as Dots from './dots-icon.svg';
export * as OneDayJob from './one-day-job.svg';
export * as GraduateIcon from './graduate-icon.svg';

export * as PrimaryLogo from './logo.svg';
export * as SecondaryLogo from './logo-secondary.svg';