import { Metadata } from "next";
import { Poppins } from "next/font/google";
import { cookies } from "next/headers";
import React from "react";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ["100","200","300","400","500","600","700","800","900",]
});


export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en">
      <head>

      </head>
      <body className={`${poppins.className}`}>

      </body>
    </html>
  );
}
